name: Build Docker images

on:
  workflow_dispatch:
  schedule:
    # run every sunday at midnight
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  generate-jobs:
    name: Generate jobs
    runs-on: ubuntu-latest
    outputs:
      biome-versions: ${{ steps.matrix.outputs.BIOME_VERSIONS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Generate matrix
        id: matrix
        run: |
          BIOME_VERSIONS=$(bun run ./scripts/generate-versions.ts)
          echo "BIOME_VERSIONS=$BIOME_VERSIONS" >> $GITHUB_OUTPUT

  build-images-arm64:
    name: ${{ matrix.biome-version.version }} (${{ matrix.variant }})
    needs: generate-jobs
    concurrency: build-images-${{ matrix.biome-version.version }}-${{ matrix.variant }}-arm64
    permissions:
      packages: write
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        variant: [alpine, debian]
        biome-version: ${{ fromJson(needs.generate-jobs.outputs.biome-versions) }}
        include:
          - variant: alpine
            version: 3.20
            runner: ubuntu-22.04
          - variant: alpine
            version: 3.20
            runner: ubuntu-22.04-arm
          - variant: debian
            version: bookworm
            runner: ubuntu-22.04
          - variant: debian
            version: bookworm
            runner: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/biomejs/biome
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ matrix.biome-version.version }}-${{ matrix.variant }}-arm64

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: push
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }} 
          file: docker/${{ matrix.variant }}.Dockerfile
          context: ./docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BIOME_VERSION=${{ matrix.biome-version.version }}
            ALPINE_VERSION=${{ matrix.version }}
            DEBIAN_VERSION=${{ matrix.version }}

  build-images-amd64:
    name: ${{ matrix.biome-version.version }} (${{ matrix.variant }})
    needs: generate-jobs
    concurrency: build-images-${{ matrix.biome-version.version }}-${{ matrix.variant }}-amd64
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        variant: [alpine, debian]
        biome-version: ${{ fromJson(needs.generate-jobs.outputs.biome-versions) }}
        include:
          - variant: alpine
            version: 3.20
            runner: ubuntu-22.04
          - variant: alpine
            version: 3.20
            runner: ubuntu-22.04-arm
          - variant: debian
            version: bookworm
            runner: ubuntu-22.04
          - variant: debian
            version: bookworm
            runner: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/biomejs/biome
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ matrix.biome-version.version }}-${{ matrix.variant }}-amd64

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: push
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }} 
          file: docker/${{ matrix.variant }}.Dockerfile
          context: ./docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BIOME_VERSION=${{ matrix.biome-version.version }}
            ALPINE_VERSION=${{ matrix.version }}
            DEBIAN_VERSION=${{ matrix.version }}
    
